export enum ActionType  {
    SETCHATS,
    SELECTCHAT, 
    LOGUSER,
    LOGOUT,
    CHANGEPASSWORD,
    SETUSERS,
    SETGROUPS,
    SELECTGROUP,
    TOGGLEFOLLOWEDGROUP,
    ADDPOST,
    SETSUBSCRIBEDGROUPS,
    SETMYGROUPS,
}